---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/authorize_dhcp_server/.aar_doc.yml
      - roles/authorize_dhcp_server/README.md
      - roles/authorize_dhcp_server/meta/argument_specs.yml
      - roles/authorize_dhcp_server/meta/main.yml
      - roles/domain_controller/.aar_doc.yml
      - roles/domain_controller/README.md
      - roles/domain_controller/meta/argument_specs.yml
      - roles/domain_controller/meta/main.yml
      - roles/linux_member/.aar_doc.yml
      - roles/linux_member/README.md
      - roles/linux_member/meta/argument_specs.yml
      - roles/linux_member/meta/main.yml
      - roles/rotate_ad_user_password/.aar_doc.yml
      - roles/rotate_ad_user_password/README.md
      - roles/rotate_ad_user_password/meta/argument_specs.yml
      - roles/rotate_ad_user_password/meta/main.yml
      - roles/testing_domain_controller/.aar_doc.yml
      - roles/testing_domain_controller/README.md
      - roles/testing_domain_controller/meta/argument_specs.yml
      - roles/testing_domain_controller/meta/main.yml
      - roles/testing_linux_member/.aar_doc.yml
      - roles/testing_linux_member/README.md
      - roles/testing_linux_member/meta/argument_specs.yml
      - roles/testing_linux_member/meta/main.yml
      - roles/testing_standalone_win/.aar_doc.yml
      - roles/testing_standalone_win/README.md
      - roles/testing_standalone_win/meta/argument_specs.yml
      - roles/testing_standalone_win/meta/main.yml
      - roles/testing_win_member/.aar_doc.yml
      - roles/testing_win_member/README.md
      - roles/testing_win_member/meta/argument_specs.yml
      - roles/testing_win_member/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.ad'
jobs:
  docs_authorize_dhcp_server:
    name: Generate authorize_dhcp_server role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.ad
          ref: main
      - name: Generate authorize_dhcp_server role documentation
        working-directory: 'trippsc2.ad'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/authorize_dhcp_server
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update authorize_dhcp_server role documentation." || /bin/true
          git push origin main
          deactivate
  docs_domain_controller:
    name: Generate domain_controller role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.ad
          ref: main
      - name: Generate domain_controller role documentation
        working-directory: 'trippsc2.ad'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/domain_controller
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update domain_controller role documentation." || /bin/true
          git push origin main
          deactivate
    needs: docs_authorize_dhcp_server
  docs_linux_member:
    name: Generate linux_member role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.ad
          ref: main
      - name: Generate linux_member role documentation
        working-directory: 'trippsc2.ad'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/linux_member
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update linux_member role documentation." || /bin/true
          git push origin main
          deactivate
    needs: docs_domain_controller
  docs_rotate_ad_user_password:
    name: Generate rotate_ad_user_password role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.ad
          ref: main
      - name: Generate rotate_ad_user_password role documentation
        working-directory: 'trippsc2.ad'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/rotate_ad_user_password
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update rotate_ad_user_password role documentation." || /bin/true
          git push origin main
          deactivate
    needs: docs_linux_member
  docs_testing_domain_controller:
    name: Generate testing_domain_controller role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.ad
          ref: main
      - name: Generate testing_domain_controller role documentation
        working-directory: 'trippsc2.ad'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/testing_domain_controller
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update testing_domain_controller role documentation." || /bin/true
          git push origin main
          deactivate
    needs: docs_rotate_ad_user_password
  docs_testing_linux_member:
    name: Generate testing_linux_member role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.ad
          ref: main
      - name: Generate testing_linux_member role documentation
        working-directory: 'trippsc2.ad'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/testing_linux_member
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update testing_linux_member role documentation." || /bin/true
          git push origin main
          deactivate
    needs: docs_testing_domain_controller
  docs_testing_standalone_win:
    name: Generate testing_standalone_win role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.ad
          ref: main
      - name: Generate testing_standalone_win role documentation
        working-directory: 'trippsc2.ad'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/testing_standalone_win
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update testing_standalone_win role documentation." || /bin/true
          git push origin main
          deactivate
    needs: docs_testing_linux_member
  docs_testing_win_member:
    name: Generate testing_win_member role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.ad
          ref: main
      - name: Generate testing_win_member role documentation
        working-directory: 'trippsc2.ad'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/testing_win_member
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update testing_win_member role documentation." || /bin/true
          git push origin main
          deactivate
    needs: docs_testing_standalone_win
